# Generated by Django 4.2.3 on 2023-08-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agent', '0002_property_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
