# Generated by Django 4.2.3 on 2023-08-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agent', '0005_alter_propertyimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.FileField(upload_to='images/'),
        ),
    ]
