# Generated by Django 4.2.3 on 2023-09-30 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estate_agent', '0009_property_annual_service_charge_property_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertycoordinates',
            name='property',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='estate_agent.property'),
        ),
    ]
